#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        enable_lazy_load_no_trans: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false


camunda.bpm.admin-user:
  id: eduardo
  password: senha@eduardo
